import { GET_BRAND } from "../../queries/brands/get-brand";
import { GET_BRANDS } from "../../queries/brands/get-brands";
import client from "../../apollo.client";
import ProductsList from "../../components/ProductsList";
import Navbar from "../../components/layout/NavBar";
import Footer from "../../components/layout/Footer";

const Product = ({brand, navBar}) => {
    return (
        <>
            <Head>
                <title>{brand.name}</title>
                <meta name="description" content="Generated by create next app" />
            </Head> 
            <Navbar navBar={navBar} />
            <h2 className="pt-[80px] pl-[72px] bold font-semibold text-lg"> {brand.name} </h2>
            <ProductsList products={brand.products}/>
            <Footer navBar={navBar}/>
        </>
    );
};

export default Product;


export async function getStaticPaths() {
    const { data } = await client.query({query: GET_BRANDS})
    const paths = data.brands.map(brand => {
        return {
            params : {slug: brand.slug}
        }
    })
    return {
      paths,
      fallback: false
   };
}

export async function getStaticProps({params}) {
  const { data } = await client.query({query: GET_BRAND, variables: {slug : params.slug}})
  const brand = data.brand
  const navBar = data.navigations[0].navBar
  return {
    props: {
      brand,
      navBar
    },
 };
}