import { GET_CATEGORY } from "../../queries/categories/get-category";
import { GET_CATEGORIES } from "../../queries/categories/get-categories";
import client from "../../apollo.client";
import ProductsList from "../../components/ProductsList";
import Navbar from "../../components/layout/NavBar";
import Footer from "../../components/layout/Footer";

const Category = ({category, navBar}) => {
    return (
        <>
            <Head>
                <title>{category.name}</title>
                <meta name="description" content="Generated by create next app" />
            </Head> 
            <Navbar navBar={navBar} />
            <h2 className="pt-[80px] pl-[72px] bold font-semibold text-lg"> Nos {category.name} </h2>
            <ProductsList products={category.products}/>
            <Footer navBar={navBar} />
        </>
    );
};

export default Category;


export async function getStaticPaths() {
    const { data } = await client.query({query: GET_CATEGORIES})
    const paths = data.categories.map(category => {
        return {
            params : {slug: category.slug}
        }
    })
    return {
      paths,
      fallback: false
   };
}

export async function getStaticProps({params}) {
  const { data } = await client.query({query: GET_CATEGORY, variables: {slug : params.slug}})
  const category = data.category
  const navBar = data.navigations[0].navBar
  return {
    props: {
      category,
      navBar
    },
 };
}