import { GET_PRODUCT } from "../../queries/products/get-product";
import { GET_PRODUCTS } from "../../queries/products/get-products";
import client from "../../apollo.client";
import CardProduct from "../../components/CardProduct";
import Navbar from "../../components/layout/NavBar";
import Footer from "../../components/layout/Footer"
import Head from "next/head";

const Product = ({product}) => {
    return (
        <>
        <Head>
          <title>{product.name}</title>
          <meta name="description" content="Generated by create next app" />
        </Head> 
        <Navbar navBar={product.navigation.navBar} />
        <CardProduct product={product}/>
        <Footer navBar={product.navigation.navBar}/>
        </>
    );
};

export default Product;


export async function getStaticPaths() {
    const { data } = await client.query({query: GET_PRODUCTS})
    const paths = data.products.map(product => {
        return {
            params : {slug: product.slug}
        }
    })
    return {
      paths,
      fallback: false
   };
}

export async function getStaticProps({params}) {
  const { data } = await client.query({query: GET_PRODUCT, variables: {slug : params.slug}})
  return {
    props: {
      product: data.product,
    },
 };
}