import React from "react";
import { BsTelephoneFill } from "react-icons/bs";
import { GrMail } from "react-icons/gr";
import { HiLocationMarker } from "react-icons/hi";
import {
  FaInstagram,
  FaTwitter,
  FaYoutube,
  FaPinterest,
  FaGithub,
} from "react-icons/fa";
import NavBar from "../components/layout/NavBar";
import client from "../apollo.client";
import { NAVIGATION } from "../queries/navigation";
import Footer from "../components/layout/Footer";

function ContactPage({navBar}) {
  return (
    <>
      <Head>
        <title>Contact</title>
        <meta name="description" content="Generated by create next app" />
      </Head> 
      <div className="w-screen md:h-screen h-auto">
          <NavBar navBar={navBar}/>
        <div className="flex justify-around items-center mx-20 md:flex-row flex-col">
          {/* textual content */}
          <div className="md:w-1/2 w-full md:p-10 my-10 md:my-0  flex-col">
            <h1 className="text-4xl font-semibold text-white ">Contact</h1>
            <p className="text-gray font-semibold text-sm my-5">
              Contactez notre équipe et on reviendra vers vous rapidement !
            </p>
            <div className="flex-col my-20 gap-5 flex  ">
              <div className="flex gap-5 p-4 border border-gray hover:border-blue md:w-1/2 w-full rounded-lg group cursor-pointer items-center">
                <BsTelephoneFill className="text-xl text-gray  group-hover:text-white" />
                <p className="text-gray text-base font-semibold group-hover:text-white">
                  +33 9 40 67 24 57
                </p>
              </div>
              <div className="flex gap-5 p-4 border border-gray hover:border-blue md:w-1/2 w-full rounded-lg group cursor-pointer items-center">
                <GrMail className="text-xl text-gray  group-hover:text-white" />
                <p className="text-gray text-base font-semibold group-hover:text-white">
                  info@music.com
                </p>
              </div>
              <div className="flex gap-5 p-4 border border-gray hover:border-blue md:w-1/2 w-full rounded-lg group cursor-pointer items-center">
                <HiLocationMarker className="text-xl text-gray  group-hover:text-white" />
                <p className="text-gray text-base font-semibold group-hover:text-white">
                  Paris, FRANCE
                </p>
              </div>
            </div>

            <div className="flex gap-8  justify-center md:justify-start ">
              <FaInstagram className="text-2xl text-white hover:text-blue cursor-pointer" />
              <FaTwitter className="text-2xl text-white hover:text-blue cursor-pointer" />
              <FaYoutube className="text-2xl text-white hover:text-blue cursor-pointer" />
              <FaPinterest className="text-2xl text-white hover:text-blue cursor-pointer" />
              <FaGithub className="text-2xl text-white hover:text-blue cursor-pointer" />
            </div>
          </div>
          {/* Contact form */}
          <div className="bg-white p-10 rounded-lg mt-10 shadow-md">
            <form>
              <div className="grid xl:grid-cols-2 xl:gap-10">
                <input
                  type="text"
                  name="first_name"
                  id="first_name"
                  className="form-control block w-full px-3 py-2 mb-5 text-base font-normal text-grey bg-white bg-clip-padding border border-solid border-gray-300 rounded-md transition ease-in-out m-0 focus:text-grey focus:bg-white focus:border-blue-600 focus:outline-none"
                  placeholder="Prénom "
                  required={true}
                />

                <input
                  type="text"
                  name="last_name"
                  id="last_name"
                  className="form-control block w-full px-3 py-2 mb-5 text-base font-normal text-grey bg-white bg-clip-padding border border-solid border-gray-300 rounded-md transition ease-in-out m-0 focus:text-grey focus:bg-white focus:border-blue-600 focus:outline-none"
                  placeholder="Nom "
                  required=""
                />
              </div>
              <input
                type="email"
                name="email"
                className="form-control block w-full px-3 py-2 mb-5 text-base font-normal text-grey bg-white bg-clip-padding border border-solid border-gray-300 rounded-md transition ease-in-out m-0 focus:text-grey focus:bg-white focus:border-blue-600 focus:outline-none"
                placeholder="Email "
                required={true}
              />
              <input
                type="text"
                name="subject"
                className="form-control block w-full px-3 py-2 mb-5 text-base font-normal text-grey bg-white bg-clip-padding border border-solid border-gray-300 rounded-md transition ease-in-out m-0 focus:text-grey focus:bg-white focus:border-blue-600 focus:outline-none"
                placeholder="Sujet "
                required={true}
              />

              <div className="flex justify-center">
                <textarea
                  className="form-control block w-full px-3 py-2 mb-5 text-base font-normal text-grey bg-white bg-clip-padding border border-solid border-gray-300 rounded-md transition ease-in-out m-0 focus:text-grey focus:bg-white focus:border-blue-600 focus:outline-none"
                  id="exampleFormControlTextarea1"
                  rows="3"
                  placeholder="Votre message"
                  required={true}
                ></textarea>
              </div>

              <button
                type="submit"
                className="uppercase text-white bg-black hover:bg-blue focus:ring-4 focus:outline-none focus:ring-blue font-medium rounded-lg text-sm w-full sm:w-auto px-5 py-2.5 text-center"
              >
                Envoyer
              </button>
            </form>
          </div>
        </div>
        <Footer navBar={navBar}/>
      </div>
    </>
  );
}

export default ContactPage;

export async function getStaticProps() {
  const { data } = await client.query({query: NAVIGATION})
  const navBar = data.navigations[0].navBar
  return {
    props: {
      navBar
    },
 };
}

