
import { GET_PAGE_BY_SLUG } from "../queries/pages/get-page";
import client from "../apollo.client";
import ProductsList from "../components/ProductsList";
import NavBar from "../components//layout/NavBar"
import Category from "../components/Category";
import Newslatter from "../components/Newslatter";
import Footer from "../components/layout/Footer";
import {BsFillArrowDownCircleFill} from "react-icons/bs"
import Head from "next/head";


export default function Home({page, products, navBar}) {
  return (
    <>
      <Head>
        <title>Acceuil</title>
        <meta name="description" content="Generated by create next app" />
      </Head> 
    <NavBar navBar={navBar}/>
    <div className="relative pt-[70px]">
    <img src={page.heroBackground[0].url} className='h-96 md:h-full w-full'/>
    <div className="flex flex-col items-center md:absolute md:bottom-10 md:right-0 text-blue text-sm md:text-base uppercase animate-bounce font-bold "> <p className="pb-1"> Viens découvrir notre sélection du moment !</p> <BsFillArrowDownCircleFill size={25}/>   </div>
    </div>
    <ProductsList products={products}/>
    <Category/>
    <Newslatter image={page.heroBackground[1].url}/>
    <Footer navBar={navBar} />
    </>
  )
}




export async function getStaticProps() {
  const { data } = await client.query({query: GET_PAGE_BY_SLUG, variables: {slug : 'home'}})
  const page = data.page
  const products = data.products.slice(0,5)
  const navBar = data.page.navigation.navBar
  return {
    props: {
      page,
      products,
      navBar
    },
 };
}